repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.2
  hooks:
    - id: ruff
      
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.1
  hooks:
    - id: mypy
      additional_dependencies:
        - sqlmodel
        # - types-python-dotenv
        # - types-pytest
        # - types-psycopg2
        # - httpx
