services:
  web:
    image: euanoturner/pronunciation-model:${IMAGE_TAG}
    ports:
      - "8001:8001"
    restart: unless-stopped
    profiles:
      - dev
      - prod
    networks:
      - parrot-network

  test:
    build:
      context: .
      target: test
    profiles:
      - test

networks:
  parrot-network:
    name: parrot-network
    external: true