services:
  multi-lang-model:
    image: euanoturner/pronunciation-model:${IMAGE_TAG}
    deploy:
      replicas: 2
    restart: unless-stopped
    profiles:
      - dev
      - prod
    networks:
      - parrot-model-network

  load-balancer:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    profiles:
      - dev
      - prod
    networks:
      - parrot-network
      - parrot-model-network
    depends_on:
      - multi-lang-model

  test:
    build:
      context: .
      target: test
    profiles:
      - test

networks:
  parrot-network:
    name: parrot-network
    external: true
  parrot-model-network:
    driver: bridge