services:
  web:
    image: euanoturner/pronunciation-model:${IMAGE_TAG}
    deploy:
      replicas: 2
    restart: unless-stopped
    profiles:
      - dev
      - prod
    networks:
      - parrot-model-network

  load-balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    profiles:
      - dev
      - prod
    networks:
      - parrot-network
      - parrot-model-network
    depends_on:
      - web

  test:
    build:
      context: .
      target: test
    profiles:
      - test

networks:
  parrot-network:
    name: parrot-network
    external: true
  parrot-model-network:
    driver: bridge