[tool.ruff]
line-length = 120

[tool.ruff.lint]
# E: pycodestyle errors
# F: Pyflakes rules
# I: isort rules
select = ["E", "F", "I"]

ignore = ["E501"] # long lines handled by formatter

[tool.ruff.lint.isort]

lines-after-imports = 2

[tool.ruff.format]

quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.mypy]

python_version = "3.11" # version in docker image
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true